name: Deploy Spring Boot to Railway

on:
  push:
    branches:
      - main  # Chạy khi có commit mới trên branch main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build Spring Boot app
        run: mvn clean package -DskipTests

      - name: Deploy to Railway
        run: |
          curl -fsSL https://railway.app/install.sh | sh
          railway login --token ${{ secrets.RAILWAY_API_KEY }}
          railway up
